CREATE DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	MATRICULA CHAR(12) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	ID_CARGO INT
);

CREATE TABLE CARGO(
	IDCARGO INT PRIMARY KEY AUTO_INCREMENT,
	CARGO VARCHAR(30) NOT NULL
);

CREATE TABLE FUNCIONARIO_UPDATE(
	IDFUNCIONARIO INT,
	NOME VARCHAR(30),
	MATRICULA CHAR(12),
	SALARIO DECIMAL(10,2),
	SALARIO_AT DECIMAL(10,2),
	ID_CARGO INT
);

DELIMITER ?

CREATE PROCEDURE ATUALIZAR_SALARIO()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VIDFUNCIONARIO, VID_CARGO INT;
	DECLARE VNOME VARCHAR(30);
	DECLARE VMATRICULA CHAR(12);
	DECLARE VSALARIO DECIMAL(10,2);
	DECLARE VSALARIO_AT DECIMAL(10,2);

	DECLARE REG CURSOR FOR
		SELECT IDFUNCIONARIO, NOME, MATRICULA, SALARIO, ID_CARGO FROM FUNCIONARIO;

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG;

	REPEAT

		FETCH REG INTO VIDFUNCIONARIO, VNOME, VMATRICULA, VSALARIO, VID_CARGO;

		IF NOT FIM THEN

			IF VSALARIO < 2000 THEN

				SET VSALARIO = VSALARIO + (VSALARIO * 0.5);

			END IF;

			SET VSALARIO_AT = VSALARIO;

			INSERT INTO FUNCIONARIO_UPDATE VALUES(VIDFUNCIONARIO, VNOME, VMATRICULA, VSALARIO, VSALARIO_AT, VID_CARGO);

		END IF;

	UNTIL FIM END REPEAT;

	CLOSE REG;

END
?

DELIMITER ;

CALL ATUALIZAR_SALARIO();
