CREATE DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	MATRICULA CHAR(12) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	ID_CARGO INT
);

CREATE TABLE CARGO(
	IDCARGO INT PRIMARY KEY AUTO_INCREMENT,
	CARGO VARCHAR(30) NOT NULL
);

CREATE TABLE FUNCIONARIO_UPDATE(
	IDFUNCIONARIO INT,
	NOME VARCHAR(30),
	MATRICULA CHAR(12),
	SALARIO DECIMAL(10,2),
	SALARIO_AT DECIMAL(10,2),
	ID_CARGO INT
);
