CREATE DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	MATRICULA CHAR(12) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	ID_CARGO INT
);

CREATE TABLE CARGO(
	IDCARGO INT PRIMARY KEY AUTO_INCREMENT,
	CARGO VARCHAR(30) NOT NULL
);

CREATE TABLE FUNCIONARIO_UPDATE(
	IDFUNCIONARIO INT,
	NOME VARCHAR(30),
	MATRICULA CHAR(12),
	SALARIO DECIMAL(10,2),
	SALARIO_AT DECIMAL(10,2),
	ID_CARGO INT
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_CARGO
FOREIGN KEY(ID_CARGO) REFERENCES CARGO(IDCARGO);


INSERT INTO CARGO VALUES(NULL, 'ANALISTA DE DADOS');
INSERT INTO CARGO VALUES(NULL, 'DEV BACKEND');
INSERT INTO CARGO VALUES(NULL, 'DEV FRONTEND');
INSERT INTO CARGO VALUES(NULL, 'ENGENHEIRO DE DADOS');
INSERT INTO CARGO VALUES(NULL, 'DEVOPS');
INSERT INTO CARGO VALUES(NULL, 'ANALISTA QA');
INSERT INTO CARGO VALUES(NULL, 'ANALISTA DE SISTEMAS');

INSERT INTO FUNCIONARIO VALUES(NULL, 'ENZO SPADETTO', '20241SET0001', 1900, 1);
INSERT INTO FUNCIONARIO VALUES(NULL, 'ENZO HUBNER', '20241SET0002', 1500, 5);
INSERT INTO FUNCIONARIO VALUES(NULL, 'VINICIUS', '20241SET0003', 2500, 2);
INSERT INTO FUNCIONARIO VALUES(NULL, 'SAMUEL', '20241SET0004', 2500, 2);
INSERT INTO FUNCIONARIO VALUES(NULL, 'MARIANA', '20241SET0005', 2000, 3);
INSERT INTO FUNCIONARIO VALUES(NULL, 'NICOLAS', '20241SET0006', 2400, 6);
INSERT INTO FUNCIONARIO VALUES(NULL, 'REFAEL', '20241SET0007', 2300, 7);
INSERT INTO FUNCIONARIO VALUES(NULL, 'JOAO', '20241SET0008', 2000, 3);
INSERT INTO FUNCIONARIO VALUES(NULL, 'FILIPE', '20241SET0009', 5000, 4);
INSERT INTO FUNCIONARIO VALUES(NULL, 'DAIANE', '20241SET0010', 2000, 3);
INSERT INTO FUNCIONARIO VALUES(NULL, 'MARCOS', '20241SET0011', 1900, 4);




DELIMITER ?

CREATE PROCEDURE ATUALIZAR_SALARIO()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VIDFUNCIONARIO, VID_CARGO INT;
	DECLARE VNOME VARCHAR(30);
	DECLARE VMATRICULA CHAR(12);
	DECLARE VSALARIO DECIMAL(10,2);
	DECLARE VSALARIO_AT DECIMAL(10,2);

	DECLARE REG CURSOR FOR
		SELECT IDFUNCIONARIO, NOME, MATRICULA, SALARIO, ID_CARGO FROM FUNCIONARIO;

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG;

	REPEAT

		FETCH REG INTO VIDFUNCIONARIO, VNOME, VMATRICULA, VSALARIO, VID_CARGO;

		IF NOT FIM THEN

			IF VSALARIO < 2000 THEN

				SET VSALARIO = VSALARIO + (VSALARIO * 0.5);

			END IF;

			SET VSALARIO_AT = VSALARIO;

			INSERT INTO FUNCIONARIO_UPDATE VALUES(VIDFUNCIONARIO, VNOME, VMATRICULA, VSALARIO, VSALARIO_AT, VID_CARGO);

		END IF;

	UNTIL FIM END REPEAT;

	CLOSE REG;

END
?

DELIMITER ;

CALL ATUALIZAR_SALARIO();
